name: Build SGX Docker

on:
  push:
    branches: 
      - 'release/**'
      - 'pre-release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test sgx with Docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push sgx docker
        run: |
          cd docker
          docker compose build raiko --no-cache
          ./push_image.sh ${{ github.ref_name }}
        shell: bash
